version: '3'

services:
  link:
    build: .
    restart: always
    environment:
      DATABASE_URL: 'postgresql://link_db:mypass@app_postgres:5432/link_db?sslmode=disable'
      PORT: '8080'
    ports:
      - 8080:8080

  app_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: link_db
      POSTGRES_DB: link_db
    ports:
      - 5432:5432
